### ISSUE TITLE
Make a startUp animation - Duration should be 1 second

### ISSUE THREAD

**Issue by ShivamTyagi12345** [Robotics-Club-NIT-Patna/roboticsclubnitpweb#67]

**Comment by SudhansuuRanjan** [comment]
I wanna working on it.

**Comment by ShivamTyagi12345** [comment]
update  on the task @SudhansuuRanjan

**Comment by SudhansuuRanjan** [comment]
The .json  website loader I made is not playing using the  react-lottie-json package🥲

I tried playing random loaders on the internet they are playing but my file is not😵

**Comment by ShivamTyagi12345** [comment]
> The .json website loader I made is not playing using the react-lottie-json packagesmiling_face_with_tear
> 
> I tried playing random loaders on the internet they are playing but my file is notdizzy_face

Use some random loaders and style the whole component using css

**Comment by SudhansuuRanjan** [comment]
Okay 🙂🙂

**Comment by SudhansuuRanjan** [comment]
The svg playback problem is solved now.
But there is no electricity 🥺🥺 when it comes I will be committing the loader part
